services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: student_management
    ports:
      - 3306:3306
    volumes:
      - data://var/lib/mysql
    restart: always

volumes:
  data: